repos:
  - repo: https://github.com/cpp-linter/cpp-linter-hooks
    rev: v0.2.4
    hooks:
      - id: clang-format
        args: [--style=Google]
      - id: clang-tidy
        args: [--checks=-clang-diagnostic-c99-extensions, -p=build]

