name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up CMake
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake
      shell: bash

    - name: Configure and build AlphaLogosTests
      run: |
        mkdir build
        cd build
        cmake .. --target AlphaLogosTests
        make AlphaLogosTests
      working-directory: ${{ github.workspace }}

    - name: Run AlphaLogosTests
      run: |
        cd build
        ./AlphaLogosTests
      working-directory: ${{ github.workspace }}
